#!/bin/bash

TODAY=$(date "+%Y-%m-%d")
echo "TODAY="$TODAY

SERVER_ID=`mysql -uroot -proot -Dsl -s -N -e "SELECT id FROM server WHERE host='"$HOST"'"`
echo "SERVER_ID="$SERVER_ID

mysql -uroot -proot -Dsl -e "DELETE FROM speed WHERE create_at>'"$TODAY"'"
mysql -uroot -proot -Dsl -e "DELETE FROM conns WHERE create_at>'"$TODAY"'"
