#!/bin/bash

TODAY=$(date "+%Y-%m-%d")
echo "TODAY="$TODAY

mysql -uroot -proot -Dsl -e "DELETE FROM speed WHERE create_at>'"$TODAY"'"
mysql -uroot -proot -Dsl -e "DELETE FROM conns WHERE create_at>'"$TODAY"'"
