-- MySQL Script generated by MySQL Workbench
-- Mon Aug  5 17:42:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sl
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sl` ;

-- -----------------------------------------------------
-- Schema sl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sl` DEFAULT CHARACTER SET utf8 ;
USE `sl` ;

-- -----------------------------------------------------
-- Table `sl`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sl`.`server` ;

CREATE TABLE IF NOT EXISTS `sl`.`server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `host` VARCHAR(200) NOT NULL,
  `port` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `chart_color` CHAR(7) NOT NULL,
  `username` VARCHAR(45) NOT NULL DEFAULT 'ubuntu',
  `receiver_start` BIGINT NOT NULL DEFAULT 0,
  `transmit_start` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `host_UNIQUE` (`host` ASC));


-- -----------------------------------------------------
-- Table `sl`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sl`.`server` ;

CREATE TABLE IF NOT EXISTS `sl`.`server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `host` VARCHAR(200) NOT NULL,
  `port` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `chart_color` CHAR(7) NOT NULL,
  `username` VARCHAR(45) NOT NULL DEFAULT 'ubuntu',
  `receiver_start` BIGINT NOT NULL DEFAULT 0,
  `transmit_start` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `host_UNIQUE` (`host` ASC));


-- -----------------------------------------------------
-- Table `sl`.`speed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sl`.`speed` ;

CREATE TABLE IF NOT EXISTS `sl`.`speed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `server_id` INT NOT NULL,
  `receive` BIGINT NOT NULL DEFAULT 0,
  `transmit` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `sl`.`conns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sl`.`conns` ;

CREATE TABLE IF NOT EXISTS `sl`.`conns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `server_id` INT NOT NULL,
  `conns` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `sl`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sl`.`colors` ;

CREATE TABLE IF NOT EXISTS `sl`.`colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `color` CHAR(7) NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sl`.`colors`
-- -----------------------------------------------------
START TRANSACTION;
USE `sl`;
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#FFB3A7');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#ED5736');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#F00056');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#F47983');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#8C4356');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#9D2933');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#FF0097');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#A98175');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#FFF143');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#FFA631');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#F0C239');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#B35C44');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#60281E');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#CA6924');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#BDDD22');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#789262');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#0C8918');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#BBCDC5');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#424C50');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#177CB0');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#3EEDE7');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#4B5CC4');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#2E4E7E');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#425066');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#8D4BBB');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#815476');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#003371');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#801DAE');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#B0A4E3');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#75878A');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#519A73');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#88ADA6');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#EEDEB0');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#725E82');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#493131');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#F2BE45');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '#BACAC6');
INSERT INTO `sl`.`colors` (`id`, `create_at`, `update_at`, `deleted`, `color`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '$A7BE44');

COMMIT;

