#!/bin/bash
IP=$1
PORT=$2
TITLE=$3
REGION=$4
COUNTRY=$5
AUTO=$6

echo "IP="$IP",     PORT="$PORT",    TITLE="$TITLE
COLOR_NUM=`mysql -uroot -proot -Dsl -s -N -e "SELECT COUNT(*) FROM colors;"`
echo "COLOR_NUM="$COLOR_NUM

SERVER_COUNT=`mysql -uroot -proot -Dsl -s -N -e "SELECT id FROM server ORDER BY id DESC LIMIT 0, 1;"`
echo "SERVER_COUNT="$SERVER_COUNT

COLOR_ID=$[$[$SERVER_COUNT+1] % $COLOR_NUM]
echo "COLOR_ID="$COLOR_ID

COLOR=`mysql -uroot -proot -Dsl -s -N -e "SELECT color FROM colors WHERE id=$COLOR_ID"`
echo "COLOR="$COLOR

if [ ! -n "$COUNTRY" ]
then
    mysql -uroot -proot -Dsl -e "INSERT INTO server(host, port, title, chart_color, region, auto)VALUES('"$IP"',"$PORT",'"$TITLE"','"$COLOR"', '"$REGION"', 1)"
else
    if [ ! -n "$AUTO" ]
    then
        mysql -uroot -proot -Dsl -e "INSERT INTO server(host, port, title, chart_color, region, country)VALUES('"$IP"',"$PORT",'"$TITLE"','"$COLOR"', '"$REGION"', '"$COUNTRY"')"
    else
        mysql -uroot -proot -Dsl -e "INSERT INTO server(host, port, title, chart_color, region, country, auto)VALUES('"$IP"',"$PORT",'"$TITLE"','"$COLOR"', '"$REGION"', '"$COUNTRY"', "$AUTO")"
    fi
fi
